// Testing actions
export const GET_SUB_APP_REQUEST = 'GET_SUB_APP_REQUEST';
export const GET_SUB_APP_SUCCESS = 'GET_SUB_APP_SUCCESS';
export const GET_SUB_APP_FAILED = 'GET_SUB_APP_FAILED';

// 15-Minute Reading page actions
export const GET_15_MINUTE_READING_REQUEST = 'GET_15_MINUTE_READING_REQUEST';
export const GET_15_MINUTE_READING_SUCCESS = 'GET_15_MINUTE_READING_SUCCESS';
export const GET_15_MINUTE_READING_FAILED = 'GET_15_MINUTE_READING_FAILED';

// Daily Reading page actions
export const GET_DAILY_READING_REQUEST = 'GET_DAILY_READING_REQUEST';
export const GET_DAILY_READING_SUCCESS = 'GET_DAILY_READING_SUCCESS';
export const GET_DAILY_READING_FAILED = 'GET_DAILY_READING_FAILED';

// Monthly Billing Information page actions
export const GET_MONTHLY_BILLING_INFORMATION_REQUEST = 'GET_MONTHLY_BILLING_INFORMATION_REQUEST';
export const GET_MONTHLY_BILLING_INFORMATION_SUCCESS = 'GET_MONTHLY_BILLING_INFORMATION_SUCCESS';
export const GET_MONTHLY_BILLING_INFORMATION_FAILED = 'GET_MONTHLY_BILLING_INFORMATION_FAILED';
